sudo: false

os:
  - linux

language:
  - c

cache:
  - ccache

services:
  - docker

script:
  - echo FROM aplattner/arch-glvnd-meson:v1 > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t withgit .;
  - docker run --volume $HOME/.ccache:/root/.ccache withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC meson build && ninja -C build test"
