sudo: false

os:
  - linux

language:
  - c

cache:
  - ccache

services:
  - docker

script:
  - echo FROM aplattner/arch-glvnd-meson:v2 > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t withgit .;
  - docker run --volume $HOME/.ccache:/root/.ccache withgit /bin/sh -c "Xvfb :3 & cd /root && TRAVIS=true CC=$CC meson build && DISPLAY=:3 ninja -C build test"
